### ISSUE TITLE
Test file path not found when description contains escaped quotes

### ISSUE THREAD

**Issue by xfh** [fadc80/karma-sonarqube-reporter#12]
When you have a description containing escaped strings as bellow, the test file path cannot be found:
```
it('should return false for "\'\'"', () => expect(isNotNullOrUndefined('')).toBe(true));
```

**Comment by maurycyg** [comment]
If you looks at the regex:
https://github.com/fadc80/karma-sonarqube-reporter/blob/master/lib/path-finder.js#L63

the escaped characters are working fine and output of executing this regex against your it with or without escaped strings is the same

```
/((describe)|(it))\s*\(\s*((?<![\\])[\`\'\"])((?:.(?!(?<![\\])\4))*.?)\4/.exec(`it('should return false for "\'\'"', () => expect(isNotNullOrUndefined('')).toBe(true));`)

["it('should return false for "'", "it", undefined, "it", "'", "should return false for "", index: 0, input: "it('should return false for "''"', () => expect(isNotNullOrUndefined('')).toBe(true));", groups: undefined]
```

```
/((describe)|(it))\s*\(\s*((?<![\\])[\`\'\"])((?:.(?!(?<![\\])\4))*.?)\4/.exec(`it('should return false for "''"', () => expect(isNotNullOrUndefined('')).toBe(true));`)

["it('should return false for "'", "it", undefined, "it", "'", "should return false for "", index: 0, input: "it('should return false for "''"', () => expect(isNotNullOrUndefined('')).toBe(true));", groups: undefined]
```

**Comment by xfh** [comment]
The problem is that there parameter `it`, given to the function `testFile` is receiving the string `should return false for "''"`, while the name of the saved spec is `should return false for "\'\'"`.

There is some logic in `existIt` to escape quotes  of the parameter `it`, but this results in yet another non matching string: `should return false for \"\'\'\"`.

I've created a minimal reproduction repo: https://github.com/xfh/karma-sonarqube-reporter-string-escaping

When you run `npm test` you will see the output:
`Test file path not found! {"src/escapes-spec.js":{"describe":["escaped quotes"],"it":["should return false for \"\\'\\'\""]}} | escaped quotes | should return false for "''"`

**Comment by fadc80** [comment]
Thank you. I'm going to take a look at it during the next weekend. If you have found a solution, feel free to send a PR.

**Comment by fadc80** [comment]
@xfh I created a new branch with a correction. Could you verify if it was effective, please? You could use the following commands:

```
git clone https://github.com/fadc80/karma-sonarqube-reporter.git
cd karma-sonarqube-reporter-string-escaping
npm link ../karma-sonarqube-reporter
npm run test
```
**Expected result:**

> START:
>  escaped quotes
>    ✔ should return false for "''"
> Finished in 0.003 secs / 0.001 secs @ 23:16:15 GMT-0300 (Brasilia Standard Time)
> SUMMARY:
> ✔ 1 test completed

Thanks!

**Comment by xfh** [comment]
Thanks, that fixed the problem!

I've run your new version also through my original project with 900 unit tests and nothing unexpected was reported. Looks good to me.

**Comment by fadc80** [comment]
Adds @xfh and @maurycyg as a contributor for bug report.

**Comment by fadc80** [comment]
Adds @maurycyg as a contributor for bug.

**Comment by fadc80** [comment]
@all-contributors please add @maurycyg as a contributor for bug.

**Comment by fadc80** [comment]
@all-contributors please add @xfh as a contributor for bug.
