### ISSUE TITLE
Problem with enforcing reportName as function

### ISSUE THREAD

**Issue by IanMoroney** [fadc80/karma-sonarqube-reporter#14]
I have found that SonarQube.testExecution.reportPath does not accept wildcards, so i can't set SonarQube.testExecution.reportPath to './reports/*.xml'  as I get this error:

`"ERROR: Error during SonarQube Scanner execution ERROR: Error during parsing of generic test execution report '/reports/*.xml'. Look at the SonarQube documentation to know the expected XML format. ERROR: Caused by: /reports/*.xml (No such file or directory)`

So, instead I attempted to specify 'reportName' not as a function, but as a filename:

sonarqubeReporter: {
    basePath: './',        // test files folder
    filePattern: '**/*spec.ts', // test files glob pattern
    encoding: 'utf-8',          // test files encoding
    outputFolder: './reports',    // report destination
    legacyMode: false,          // report for Sonarqube < 6.2 (disabled)
    reportName: 'headlesschrome.xml'
    },

After which, the run fails with:

> 04 06 2019 15:00:16.787:ERROR [karma-server]: TypeError: reportName is not a function
    at sonarqubeReporter.specSuccess (/node_modules/karma-sonarqube-reporter/index.js:55:7)
    at sonarqubeReporter.onSpecComplete (/node_modules/karma-sonarqube-reporter/index.js:43:12)
    at Server.<anonymous> (/node_modules/karma/lib/events.js:40:26)
    at emitTwo (events.js:131:20)
    at Server.emit (events.js:214:7)

If I can't determine the name of the report statically (as the current name of the file is: headlesschrome.74.0.3729.linux.0.0.0.xml), and I can't report the filename dynamically, how am I meant to work around this?

**Comment by fadc80** [comment]
The current implementation doesn't accept defining the `reportName` option as a string, but you use a callback function to return whatever you want:

```javascript
sonarqubeReporter: {
  (metadata) => { // report name callback
     return 'headlesschrome.xml';
  }
}
```
Does it look good to you?

**Comment by IanMoroney** [comment]
will test and let you know, thank you

**Comment by fadc80** [comment]
As karma allows you to run your tests in multiple browsers, I thought defining the report name dinamically would be a good idea. It was just after publishing the first version that I ran into the same problem you just found. As there were already some projects using this npm package, I decided to keep it for backward compatibility. By other hand, this [issue](https://github.com/SonarSource/SonarJS/issues/578) demands support for using wildcards. So, maybe it is going to become usefull in the future. It would be easy to change the code to accept both: dynamic (callback function) and static (file name) report names. Unfortunetaly, in this moment I'm very busy. Feel free to open a PR if want.

**Comment by IanMoroney** [comment]
> The current implementation doesn't accept defining the `reportName` option as a string, but you use a callback function to return whatever you want:
> 
> ```js
> sonarqubeReporter: {
>   reportName: (metadata) => {
>      return 'headlesschrome.xml';
>   }
> }
> ```
> 
> Does it look good to you?

I can confirm this works.
Thank you
