### ISSUE TITLE
Don't use OS specific browser name in directory name while generating report

### ISSUE THREAD

**Issue by sohansoni** [fadc80/karma-sonarqube-reporter#4]
Reporter generates test report with a file name which includes the name of the browser and the OS. This makes it nondeterministic.

With these options: (I am running on Windows 10 and PhantomJs browser)

```
        sonarqubeReporter: {
            basePath: '.',
            filePattern: 'test/webapp/**/*Spec.ts',
            outputFolder: 'reports',
            encoding: 'utf-8'
        },
```

The output goes to:

`reports/phantomjs.2.1.1.windows.8.0.0.0.xml`

If my dev environment is osx and my CI environment is Unix, the coverage report will be in a different place, making it difficult to automate around.

This was issue with karma-coverage also, then they provided option to give the name of sub-directory for file location, instead of always defaulting the name to OS specific browser, please refer  https://github.com/karma-runner/karma-coverage/pull/62,  

Can you also provide the same ?

**Comment by fadc80** [comment]
I added a callback function to customize report names:
