### ISSUE TITLE
Configurable rootElementName for backward compatibility

### ISSUE THREAD

**Issue by sohansoni** [fadc80/karma-sonarqube-reporter#5]
Right now it generates report with root element as "testExecutions" which is fine for sonarqube versions before 6.2. But before 6.2, sonarqube requires report's root Element to be "unitTest". Can we make the rootElement configurable ?

**Comment by sohansoni** [comment]
I have made the changes, but somehow not able to push the new branch to origin, its saying permission issue. 
remote: Permission to fadc80/karma-sonarqube-reporter.git denied to sohansoni.
fatal: unable to access 'https://github.com/fadc80/karma-sonarqube-reporter.git/': The requested URL returned error: 403

Anyways, What i did was 

`const DEFAULT_ROOT_ELEMENT_NAME = 'testExecutions';`
`  var rootElementName = sonarqubeConfig.rootElementName || DEFAULT_ROOT_ELEMENT_NAME;`

passed this rootElementName till

```
function toXml(report, rootElementName) {
  return js2xmlparser.parse(rootElementName, report);
}
```

Can you please add this support ?

**Comment by fadc80** [comment]
Master branch is protected to keep it stable. Most github projects adopt this strategy. This explain why you had a permission issue. In fact, I haven't added a contribution guide (comming soon), but usually you should create a PR (Pull Request). 

Despite that, I think promoting backward compatibility this way would enable the generation of invalid reports. You could define any arbitrary XML root element. Also, prior to Sonarqube 6.2 a different property was used: `sonar.genericcoverage.unitTestReportPaths`. So we would have to change *README* instructions. 

I'm not sure this change would be worth. Maybe you could apply a XSL Transformation after running your tests to change the report root element. A npm script like `ng test && <xslt-comand>` could be a rasonable workaround. Another option is to fork this project and implement a solution as you wish.

**Comment by sohansoni** [comment]
Thanks Fernando for suggestions, I would still like to have these changes in your branch because I think it will create backward compatibility. 
I have created a Pull Request, kind request to you to review it.
I have updated the _README_ also.

Regarding invalid reports, I think we can add a check to allow only "`testUnits`" and "`testExecutions`" as valid values for rootElement and ignore any other value.

**Comment by sohansoni** [comment]
Hi Fernando, any thoughts ?

**Comment by fadc80** [comment]
I've just post some comments on your PR. Please check it out!

**Comment by sohansoni** [comment]
I made the changes as you suggested, can you please review them ?

**Comment by fadc80** [comment]
It was merged.

Thank you!

**Comment by sohansoni** [comment]
Thanks Fernando !
