### ISSUE TITLE
Console is flooded when the test file for a test is not found

### ISSUE THREAD

**Issue by jbardon** [fadc80/karma-sonarqube-reporter#97]
When the test file isn't found for a test, a `JSON.stringify` of all the paths.
This is really enormous when you have even only 100 unit tests and not helpful to determine which test raise the error since the console can't print all the data.

Extract of the code responsible for this:
```js
function testFile(paths, describe, it) {
  var testFile = Object.keys(paths).find(path =>
    exist(paths, path, describe, it));
  if (testFile === undefined) {
    logger.error('Test file path not found! %s | %s | %s',
        JSON.stringify(paths), describe, it);
  }
  return testFile;
}
```

I suggest to not print the paths at all. Another solution would be to display them after the describe and it so there are always printed in the console.

**Comment by paulius-p** [comment]
Hello, is it possible to release a new version including this? Reporter spams quite a bit due to failing to find dynamic test names.

**Comment by fadc80** [comment]
@paulius-p Version v1.3.2 published!
